### ISSUE TITLE
Cannot read property 1

### ISSUE THREAD

**Issue by CitizenZultron** [gemoroy/venal#4]
Select command venal sell
Export data following gets triggered

TypeError: Cannot read property '1' of null
    at Watcher.getItemName (/Users/edgar/.npm-global/lib/node_modules/venal/modules/watcher.js:14:18)
    at FSWatcher.fs.watch (/Users/edgar/.npm-global/lib/node_modules/venal/modules/watcher.js:21:27)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
➜  ~

**Comment by CitizenZultron** [comment]
I understood my mistake I was exporting all my orders instead of single orders that was what was the main issue. Should be clearer in description works great part of that. I would suggest catching that error if someone is trying to export all their orders. You may close the ticket thanks

**Comment by CitizenZultron** [comment]
Perfect little tool. Nice work windows version would be good to have too!
